#pragma config(Sensor, in1,    IRD1,           sensorPotentiometer)
#pragma config(Sensor, in2,    IRD2,           sensorPotentiometer)
#pragma config(Sensor, in3,    IRD3,           sensorPotentiometer)
#pragma config(Sensor, in4,    IRD4,           sensorPotentiometer)
#pragma config(Sensor, in5,    FL,             sensorAnalog)
#pragma config(Sensor, in6,    FR,             sensorAnalog)
#pragma config(Sensor, in7,    BL,             sensorAnalog)
#pragma config(Sensor, in8,    BR,             sensorAnalog)
#pragma config(Sensor, dgtl1,  com_P,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  com_N,          sensorDigitalIn)
#pragma config(Sensor, dgtl3,  com_E,          sensorDigitalIn)
#pragma config(Sensor, dgtl4,  com_S,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  com_W,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, S_W,            sensorDigitalIn)
#pragma config(Sensor, dgtl12, ball_T,         sensorDigitalIn)
#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightmotor,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool need_chiong=true;
bool search_ball=false;
bool scan=false;
bool approach=false;
bool ball_detected=false;
bool check_ball=false;
//bool check_orientation=false;
bool back_home=false;
bool send_ball_back=false;
bool start_game=false;
float d1,davg,dcq[2]={30,30},d2,d2raw,d2q[2],d3,d4;
float DR=35;
int initial,c_value;
int F_L,F_R,B_L,B_R,C;


int IRValue1(tSensors sensorPort, float conversionFactor = .0000469616, float k = .42)
{
	d1= ((1.0 / (SensorValue[sensorPort] * conversionFactor)) - k);
	dcq[0]=dcq[1];
	dcq[1]=d1;
	davg=(dcq[0]+dcq[1])/2.0;
	return davg;
}
int IRValue2(tSensors sensorPort, float conversionFactor = .0000469616, float k = .42)
{
	d2raw= ((1.0 / (SensorValue[sensorPort] * conversionFactor)) - k);
	d2q[0]=d2q[1];
	d2q[1]=d2raw;
	d2=(d2q[0]+d2q[1])/2.0;
	return d2;
}
int IRValue3(tSensors sensorPort, float conversionFactor = .0000469616, float k = .42)
{
	d3= ((1.0 / (SensorValue[sensorPort] * conversionFactor)) - k);
	return d3;
}
int IRValue4(tSensors sensorPort, float conversionFactor = .0000469616, float k = .42)
{
	d4= ((0.5 / (SensorValue[sensorPort] * conversionFactor)) - k);
	return d4;
}
																			void Rstartvalues ()
																			{F_L=SensorValue(FL);
																			 F_R=SensorValue(FR);
																			 B_L=SensorValue(BL);
																			 B_R=SensorValue(BR);
																			}

int orientation ()
{
	int c_value0,c_value1,c_value2,c_value3,c_value4;
	c_value0=SensorValue(com_P);
	c_value1=SensorValue(com_N);
	c_value2=SensorValue(com_E);
	c_value3=SensorValue(com_S);
	c_value4=SensorValue(com_W);
	c_value=SensorValue(com_N)+2*SensorValue(com_E)+4*SensorValue(com_S)+8*SensorValue(com_W);
	return c_value;
}

void serv(int d)
{
	motor[servo]=(1*d);
	wait1Msec(1500);
}
void smooth_serv(int p)
{
	while(motor[servo]>p)
	{
		motor[servo]=motor[servo]-1;
		wait1Msec(2);
	}
	while(motor[servo]<p)
	{
		motor[servo]=motor[servo]+1;
		wait1Msec(2);
	}
}
void move_forward(int s)
{
	motor[leftmotor]=s;

	motor[rightmotor]=s;}

void move_backward(int s)
{
	motor[leftmotor]=-s;

	motor[rightmotor]=-s;}

void turn_left(int s)
{
	motor[leftmotor]=-s;
	motor[rightmotor]=s;
}

void turn_right(int s)
{
	motor[leftmotor]=s;
	motor[rightmotor]=-s;}

void stop_motor()
{

	motor[rightmotor]=0;
	//wait1Msec(40);
	motor[leftmotor]=0;
}
																		void catching_ball()
																		{
																			serv(-125);
																			smooth_serv(30);
																			ball_detected =false;
																			check_ball =true;
																		}
																		void checking_ball()
																		{
																			if(SensorValue[ball_T]==0)
																			{
																				check_ball=false;
																				back_home=true;
																			}
																			else
																			{
																				check_ball=false;
																				clearTimer(T2);
																				search_ball=true;
																				approach=true;

																			}
																		}


																												void toggle ()
																												{
																													C=SensorValue[S_W];
																													if(SensorValue[S_W]==0 && start_game==0)
																													{wait1Msec(200);
																														start_game=true;}
																												  else if(SensorValue[S_W]==0 && start_game==1)
																												  {wait1Msec(200);
																												  	start_game=false;}
																												}

																	void R_test()
																	{


																						if(SensorValue[FR]<(F_R-40))
																						{
																							move_backward(50);
																							wait1Msec(1000);
																							turn_left(50);
																							wait1Msec(200);
																						}
																						else if(SensorValue[FL]<(F_L-50))
																						{
																							move_backward(50);
																							wait1Msec(1000);
																							turn_right(50);
																							wait1Msec(200);
																						}
																						else if(SensorValue[BR]<(B_R-40))
																						{
																							move_forward(50);
																							wait1Msec(1000);
																							turn_right(50);
																							wait1Msec(200);
																						}
																						else if(SensorValue[BL]<(B_L-20))
																						{
																							move_forward(50);
																							wait1Msec(1000);
																							turn_left(50);
																							wait1Msec(200);
																						}

																	}


										void chiong()
										{
											      clearTimer(T1);
											      clearTimer(T2);
														while(time1[T1]<2500)
													{
														//R_test();
															motor[leftmotor]=75;
	                           motor[rightmotor]=90;
												  }
											need_chiong=false;
											scan=true;
											search_ball=true;
										}


																				               void RM ()
												                                          {
												                                          	F_L=SensorValue(FL);
												                                          	F_R=SensorValue(FR);
												                                          	B_L=SensorValue(BL);
												                                          	B_R=SensorValue(BR);
												                                          }

												                               void ASB ()
																	                               {
																		                                 if (c_value == 1 || c_value== 2 || c_value== 3)
																		                                 {
																		                                   clearTimer(T2);
																		                                 }
																		                                 if(time1[T2]>30000)
																		                                 {
																			                                   while(c_value!=initial)
																			                                   {
																			                                     turn_left(25);
																			                                   }
																		                                 }
																	                               }


																																							void search()
																																							{
																																							//	clearTimer(T2);
																																							bool back_abit =true;
																																												while(scan==true && start_game==true && time1[T2]<25000)
																																												{

																																														clearTimer(T1);
																																														while(time1[T1]<950 && start_game==true && scan==true)
																																														{
																																															orientation ();
																																															toggle();
																																															R_test();
																																															IRValue1(IRD1);
																																															IRValue2(IRD2);
																																														  IRValue3(IRD3);

																																															if(d3>15)
																																															{

															                                                                      if(davg<=DR || d2 <=DR)
																																																		{
																																																			if((d3-davg)>20 ||(d3-d2)>20)
																																																		  {
																																																		  	scan=false;
																																																			 approach=true;
																																																		  }
																																																		  else
																																																		  move_forward(25); //search motion
																																																		}

																																																		else if (davg>DR && d2>DR)
																																																			move_forward(25); //search motion
																																															 }
																																															 else {
																																																		   move_backward(35);

																																																		   turn_left(30);}
																																														}

																																														clearTimer(T1);
																																														while(time1[T1]<750 && start_game==true && scan==true)
																																														{
																																															toggle();
																																															R_test();
																																															IRValue1(IRD1);
																																															IRValue2(IRD2);
																																															IRValue3(IRD3);

																																															if(d3>15)
																																															{
																																																	 if(davg<=DR || d2 <=DR)
																																																	 {
																																																		if((d3-davg)>20 ||(d3-d2)>20)
																																																		  {
																																																		  	scan=false;
																																																			 approach=true;
																																																		  }
																																																		  else
																																																		  turn_left(25); //search motion
																																																	 }

																																																	 else if (davg>DR && d2>DR)
																																																		turn_left(25); //search motion
																																															}
																																															else {
																																																		   move_backward(35);

																																																		   turn_left(30);}

																																														}
																																														clearTimer(T1);
																																														while(time1[T1]<1400 && start_game==true && scan==true)
																																														{
																																															toggle();
																																															R_test();
																																															IRValue1(IRD1);
																																															IRValue2(IRD2);
																																															IRValue3(IRD3);

																																															if(d3>15)
																																															{
														                                                                      if(davg<=DR || d2 <=DR)

																																																	{
																																																			if((d3-davg)>20 ||(d3-d2)>20)
																																																	  {
																																																	  	scan=false;
																																																		 approach=true;
																																																	  }
																																																	  else
																																																	  turn_right(25); //search motion
																																																	}

																																																	else if (davg>DR && d2>DR)
																																																	turn_right(25); //search motion
																																														   }
																																														   else {
																																																		   move_backward(35);

																																																		   turn_left(30);}

																																														}
																																														clearTimer(T1);
																																														while(time1[T1]<800 && start_game==true && scan==true)
																																														{
																																															toggle();
																																															R_test();
																																															IRValue1(IRD1);
																																															IRValue2(IRD2);
																																															IRValue3(IRD3);

																																															if(d3>15)
																																															{

															                                                                      if(davg<=DR || d2 <=DR)

																																																		{
																																																				if((d3-davg)>20 ||(d3-d2)>20)
																																																		  {
																																																		  	scan=false;
																																																			 approach=true;
																																																		  }
																																																		  else
																																																		  turn_left(25); //search motion
																																																		}

																																																		else if (davg>DR && d2>DR)
																																																			turn_left(25); //search motion
																																																}
																																																else {
																																																		   move_backward(35);

																																																		   turn_left(30);}
																																														 }
																																													}
																																													while(approach==true && start_game==true && time1[T2]<25000)
																																												  {
																																																	  toggle();
																																																		R_test();
																																																		IRValue1(IRD1);
																																																		IRValue2(IRD2);
																																																		IRValue3(IRD3);
																																																		if(d3>15)
																																																		{
																																																				if(d2<=DR || davg<=DR)
																																																				{
																																																						if(d2>8.5 && davg>8.5)
																																																						move_forward(20);
																																																				    else
																																																				    {
																																																				    	approach=false;

																																																				    	search_ball=false;
																																																				    	ball_detected=true;
																																																				    }
																																																		    }
																																																		    else if(d2>DR && davg>DR)
																																																		    {
																																																		    	approach=false;
																																																		      scan=true;
																																																		    }
																																																		 }
																																																		 else
																																																		 {
																																																		   move_backward(35);

																																																		   turn_left(30);}
																																												  }

																																									while( time1[T2]>=25000 && c_value!=initial && start_game==true)
																																									{
																																										orientation ();
																																										toggle();
																																										if (back_abit==true)
																																										{
																																										move_backward(30);
																																										wait1Msec(1000);
																																										back_abit=false;
																																									  }

																																									  else if(c_value==initial)
																																									  {clearTimer(T2);}
																																										else
																																										{turn_left(30);}

																																									}

																																							}


															void send_home()
																{
																	orientation ();
																	if(c_value==initial)
                                {

																						if(d4>15.00 )
																					{
																						motor[leftmotor]=-70;
																							motor[rightmotor]=-70;
																						}

																						else
																						{stop_motor();
																							back_home=false;
																							send_ball_back=true;

																						}
																}
																 else
																   {if(c_value==6 || c_value==14 || c_value==12|| c_value==13)
																     turn_right(25);
																   else
																     turn_left(25);}
																}

																void drop_ball()

																{ stop_motor();
																	wait1Msec(200);
																	if(SensorValue[BR]<(B_R-40)||SensorValue[BL]<(B_L-20))
								                 {     stop_motor();
								                       smooth_serv(85);
																				send_ball_back=false;
																				need_chiong=true;
																				wait1Msec(1500);}
																	else
																	{//turn_left(30);
																		move_backward(30);
																		send_ball_back=false;
																		back_home=true;}
																}

task main()
{
wait1Msec(1500);
Rstartvalues ();
orientation();
initial = c_value;
smooth_serv(85);

while(1)
{ //orientation();
	//IRValue3(IRD3);
			//	RM();
				while(start_game==false)
				{
				toggle();
				stop_motor();
				}
				while(start_game==true)
				{
							  while(need_chiong==true && start_game==true)
									{
										toggle();
								    chiong();
									}

									while(search_ball==true && start_game==true)
									{
										orientation ();
										search();
									}

									while(ball_detected==true && start_game==true)
									{
										stop_motor();
										catching_ball();
										toggle();
									}

									while(check_ball==true && start_game==true)
									{
										checking_ball();
										toggle();
									}


									while(back_home==true && start_game==true)
									{
									//	orientation ();
										IRValue4(IRD4);
										send_home();
										R_test();
										toggle();
									}

									while(send_ball_back==true && start_game==true)
									{
										drop_ball();
										toggle();
									}

				}

}
}
